HouseTARgv20/Models/House/HouseListViewModel.cs
using System;

namespace HouseTARgv20.Models.House
{
    public class HouseListViewModel
    {
        public Guid? Id { get; set; }
        public string Address { get; set; }
        public int HouseNumber { get; set; }
        public int Floors { get; set; }
        public int Rooms { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime ModifiedAt { get; set; }

    }
}

HouseTARgv20/Models/House/HouseViewModel.cs
using System;

namespace HouseTARgv20.Models.House
{
    public class HouseViewModel
    {
        public Guid? Id { get; set; }
        public string Address { get; set; }
        public int HouseNumber { get; set; }
        public int Floors { get; set; }
        public int Rooms { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime ModifiedAt { get; set; }
    }
}

HouseTARgv20/Controllers/HouseController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;
using HouseTARgv20.Core.Dto;
using HouseTARgv20.Core.ServiceInterface;
using HouseTARgv20.Data;
using HouseTARgv20.Models.House;

namespace HouseTARgv20.Controllers
{
    public class HouseController : Controller
    {
        private readonly HouseDbContext _context;
        private readonly IHouseService _houseService;

        public HouseController
            (
                HouseDbContext context,
                IHouseService houseService
            )
        {
            _context = context;
            _houseService = houseService;
        }


        public IActionResult Index()
        {
            var result = _context.House
                .Select(x => new HouseListViewModel
                {
                    Id = x.Id,
                    Address = x.Address,
                    HouseNumber = x.HouseNumber,
                    Floors = x.Floors,
                    Rooms = x.Rooms,
                    Price = x.Price,
                    Description = x.Description
                }).ToList();

            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var house = await _houseService.Delete(id);

            if (house == null)
            {
                RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Add()
        {
            HouseViewModel model = new HouseViewModel();

            return View("Edit", model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(HouseViewModel model)
        {
            var dto = new HouseDto()
            {
                Id = model.Id,
                Address = model.Address,
                HouseNumber = model.HouseNumber,
                Floors = model.Floors,
                Rooms = model.Rooms,
                Price = model.Price,
                Description = model.Description,
                CreatedAt = model.CreatedAt,
                ModifiedAt = model.ModifiedAt
            };

            var result = await _houseService.Add(dto);
            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var house = await _houseService.Edit(id);
            if (house == null)
            {
                return NotFound();
            }

            var model = new HouseViewModel();

            model.Id = house.Id;
            model.Address = house.Address;
            model.HouseNumber = house.HouseNumber;
            model.Floors = house.Floors;
            model.Rooms = house.Rooms;
            model.Price = house.Price;
            model.Description = house.Description;
            model.CreatedAt = house.CreatedAt;
            model.ModifiedAt = house.ModifiedAt;

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Update(HouseViewModel model)
        {
            var dto = new HouseDto()
            {
                Id = model.Id,
                Address = model.Address,
                HouseNumber = model.HouseNumber,
                Floors = model.Floors,
                Rooms = model.Rooms,
                Price = model.Price,
                Description = model.Description,
                CreatedAt = model.CreatedAt,
                ModifiedAt = model.ModifiedAt
            };

            var result = await _houseService.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), model);
        }
    }
}

HouseTARgv20/Views/House/Edit.cshtml
@model HouseTARgv20.Models.House.HouseViewModel


@if (Model.Id.HasValue)
{
    <h1>Update</h1>
}
else
{
    <h1>Add</h1>
}



<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />
        <input asp-for="ModifiedAt" type="hidden" />

        <div class="form-group row">
            <label asp-for="Address" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Address" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="HouseNumber" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="HouseNumber" class="form-control" min="1" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Floors" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Floors" class="form-control" min="1"/>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Rooms" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Rooms" class="form-control" min="1" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Price" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Price" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Description" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <textarea asp-for="Description" class="form-control" rows="5"></textarea>
            </div>
        </div>

        @if (Model.Id.HasValue)
        {
            <input asp-action="update" asp-controller="house" type="submit" class="btn btn-primary" value="Update">
            <input asp-action="delete" asp-controller="house" asp-for="Id" type="submit" class="btn btn-danger" value="Delete">
        }
        else
        {
            <input asp-action="add" asp-controller="house" type="submit" class="btn btn-primary" value="Add">
        }
        <a asp-action="index" class="btn btn-primary">Index</a>

    </form>
</div>

HouseTARgv20/Views/House/Index.cshtml
@model IEnumerable<HouseTARgv20.Models.House.HouseListViewModel>

@{
    int queueNumber = 0;
}

<div>
    <a asp-action="add" asp-controller="house" type="submit" class="btn btn-danger">Add</a>
</div>
<form method="post">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">Address</th>
                <th scope="col">HouseNumber</th>
                <th scope="col">Floors</th>
                <th scope="col">Rooms</th>
                <th scope="col">Price</th>
                <th scope="col">Description</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var house in Model)
            {
                queueNumber++;

                <tr>
                    <td class="">@queueNumber</td>
                    <td class="">@house.Address</td>
                    <td class="">@house.HouseNumber</td>
                    <td class="">@house.Floors</td>
                    <td class="">@house.Rooms</td>
                    <td class="">@house.Price</td>
                    <td class="">@house.Description</td>
                    <td>
                        <a asp-action="edit" asp-controller="house" asp-route-id="@house.Id" class="btn btn-primary">Edit</a>
                        <input asp-action="delete" asp-controller="house" asp-route-id="@house.Id" type="submit" class="btn btn-danger" value="Delete">
                    </td>


                </tr>
            }
        </tbody>
    </table>
</form>

HouseTARgv20/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] House</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="House" asp-action="Index">House</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            @DateTime.Now.Year - House - <a asp-area="" asp-page=""></a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>